### ISSUE TITLE
u-tabbar  error

### ISSUE THREAD

**Issue by bbhxwl** [umicro/uView2.0#1017]
### 版本
2.0.33

### 转载链接
[http://baidu.com/](http://baidu.com)

### 重现步骤
u-tabs.vue:228 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'rect')
    at VueComponent.setScrollLeft (u-tabs.vue:228:1)
    at eval (u-tabs.vue:251:1)

### 期望的结果是什么？
u-tabs.vue:228 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'rect')
    at VueComponent.setScrollLeft (u-tabs.vue:228:1)
    at eval (u-tabs.vue:251:1)

### 实际的结果是什么？
u-tabs.vue:228 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'rect')
    at VueComponent.setScrollLeft (u-tabs.vue:228:1)
    at eval (u-tabs.vue:251:1)

**Comment by yangle594** [comment]
试一下
<u-tabs :list="list1" @change="changeTab" :current="current" :scrollable="false"></u-tabs>
changeTab({index}) {
      this.current = index
}
change事件接收的是对象(index: 标签索引值，item: 传入的其他值)
