### ISSUE TITLE
使用vue-cli创建项目引入uView后导致H5页面一片空白

### ISSUE THREAD

**Issue by WEI4D** [umicro/uView2.0#587]
### 版本
2.0.31

### 转载链接
[github.com/WEI4D/test-uview](https://github.com/WEI4D/test-uview)

### 重现步骤
1、vue create -p dcloudio/uni-preset-vue test-uview
2、创建完项目后，根据官方文档安装配置uview
3、执行命令：npm run server
4、浏览器查看相关页面，UI未渲染，一片空白
5、执行：npm run mp-weixin
6、微信小程序页面可以正常渲染
7、注：直接拉取重现链接代码即可重现

### 期望的结果是什么？
可以正常运行，且在浏览器可以看到界面正常呈现

### 实际的结果是什么？
1、浏览器环境下，页面无法显示，表现为，一片空白
2、小程序环境下，页面可以正常显示

**Comment by donywan** [comment]
```
Uncaught TypeError: Cannot set properties of undefined (setting 'default')
    at _regeneratorRuntime (chunk-vendors.js:14112:19)
    at chunk-vendors.js:62015:99
    at chunk-vendors.js:62091:6
    at Object.ebZT (chunk-vendors.js:62137:2)
    at __webpack_require__ (index.js:854:30)
    at fn (index.js:151:20)
    at Object.a1KO (chunk-vendors.js:59530:37)
    at __webpack_require__ (index.js:854:30)
    at fn (index.js:151:20)
    at eval (main.js:3:1)
```
用uniapp cli默认模板，npm方式安装uview2，我是出现这个问题

**Comment by donywan** [comment]
> 

环境版本如下：
```
PS C:\Users\root> node -v
v14.19.3
PS C:\Users\root> npm -v
6.14.17
PS C:\Users\root> yarn -v
1.22.18
PS C:\Users\root>
```

**Comment by chenminghui-git** [comment]
![image](https://user-images.githubusercontent.com/64004615/172107943-c48180d3-26b9-413b-805b-6fe22b25ea77.png)
npx @dcloudio/uvm

**Comment by sun-sharp** [comment]
@chenminghui-git 尝试更新到最新正式版了，但是用yarn来安装还是不行的，h5界面会报错，只有npm安装没有问题，导入其它插件是没有问题的，只有使用uview2就有问题，使用最新版的uview1也有这个相同的问题

**Comment by Kaiter-Plus** [comment]
后面的问题就是导入样式的位置不对，`uview-ui/theme.scss` 应该在 uni.scss 导入，而 App.vue 导入的是 `uview-ui/index.scss`，这样子配置之后 uView 就能正常使用了

![image](https://user-images.githubusercontent.com/50108558/172572366-c3eedfbc-d3e2-4c57-9dbd-50d122fa23fd.png)
![image](https://user-images.githubusercontent.com/50108558/172572228-40ed92ad-f007-487a-ac3b-640efa323270.png)

**Comment by sun-sharp** [comment]
@Kaiter-Plus 能知道你是只运行了yarn upgrade就可以了吗，你的yarn版本是怎么样的吗
我的环境是
`
yarn -v
1.22.19
`
最后在浏览器中运行还是有问题的
![image](https://user-images.githubusercontent.com/44342546/172603565-f7cb5e16-440d-469c-a8d2-a1112e07a301.png)

**Comment by Kaiter-Plus** [comment]
@sun-sharp 我这边使用的是 pnpm，就是执行了一下 `pnpm update` 命令更新了依赖而已，使用的是 pnpm 7.1.9 版本，没有其它的操作，这个命令个 `yarn upgrade` 是一样的都只是更新依赖的操作

**Comment by sun-sharp** [comment]
@Kaiter-Plus pnpm安装在h5上运行是没有问题的，但是运行在微信小程序是不行的，会报错，我这边试过，只有用npm安装是h5端和小程序端都没问题的
这是在小程序下的问题，用pnpm安装
![image](https://user-images.githubusercontent.com/44342546/172754950-39e8aebc-623e-49ef-abf7-0deddee926fd.png)

**Comment by fengyunchangxuan** [comment]
这个问题解决了吗？我也遇到了

**Comment by fengyunchangxuan** [comment]
> 

这个问题你解决了吗？

**Comment by fengyunchangxuan** [comment]
@donywan 这个问题你解决了吗？我也遇到这个问题了

**Comment by Kaiter-Plus** [comment]
@sun-sharp 我这边测试了一下，**h5** 和 **小程序** 都没有问题

![image](https://user-images.githubusercontent.com/50108558/172757001-ee2f0d77-2622-4112-9748-c7610906cfa2.png)

![image](https://user-images.githubusercontent.com/50108558/172756907-94effb1f-bdea-4074-8dda-46616c1ce9c7.png)

**Comment by fengyunchangxuan** [comment]
@Kaiter-Plus 我这边一直都有问题

**Comment by Kaiter-Plus** [comment]
@sun-sharp 可以在项目根目录添加 `.npmrc` 文件，里面添加如下代码：
```js
shamefully-hoist=true
```

**Comment by sun-sharp** [comment]
@Kaiter-Plus 不是，你在页面使用一下组件呢，这个问题是使用组件才会出现

**Comment by Kaiter-Plus** [comment]
@sun-sharp 好像是哦，使用 pnpm h5 端使用正常但是微信小程序会报错，使用 yarn 的话微信小程序使用正常但是 h5 会报错

**Comment by sun-sharp** [comment]
@Kaiter-Plus 是的，只有使用npm安装才都没有问题

**Comment by Kaiter-Plus** [comment]
>是的，只有使用npm安装才都没有问题

是的，试了下还真是，所以其实解决方法就是直接 npm 安装就可以了🤣

**Comment by Kaiter-Plus** [comment]
@fengyunchangxuan 使用 npm 安装就可以了

**Comment by fengyunchangxuan** [comment]
@Kaiter-Plus  没用的，我就是使用的npm

**Comment by Kaiter-Plus** [comment]
@fengyunchangxuan 可以试着更新一下依赖 `npm upgrade`

**Comment by sun-sharp** [comment]
@Kaiter-Plus 能解决这个问题吗，我尝试用 uview1最新版，也是有这个问题的，版本1.7.8还是正常的，好像是从1.7.9开始，我用yarn安装插件h5端开始不行的

**Comment by Kaiter-Plus** [comment]
> 能解决这个问题吗，我尝试用 uview1最新版，也是有这个问题的，版本1.7.8还是正常的，好像是从1.7.9开始，我用yarn安装插件h5端开始不行的

@sun-sharp 直接使用 npm 安装不就可以了吗，可能是 `yarn` 和 `pnpm` 都是使用链接的方式安装依赖，而 npm 直接是本地安装的原因

**Comment by Smartiboy** [comment]
解决了吗我也遇到了相同问题

**Comment by lileltp** [comment]
一样的问题 H5下报错。小程序可以

**Comment by gaofeng2022** [comment]
@sun-sharp 跟你碰到一样的问题，pnpm安装，h5没问题，小程序报错，有解决办法吗？

**Comment by sun-sharp** [comment]
@gaofeng2022 只能使用npm安装，其它方式安装没办法，除非你不用这ui
